
# Model Training
NUM_EPISODES = 1000000
MODEL_SAVE_RATE = 100
DISCOUNT_FACTOR = .99
LEARNING_RATE = 3e-4

# Model Architecture
HIDDEN_LAYERS = 3
HIDDEN_SIZE = 32
K_PELLETS = -1
K_PLAYERS = -1
NEGATIVE_SLOPE = 0.2

# Directories
DIR_SAVED_MODELS = "saved_models"
DIR_RUNS = "runs"
DIR_RESULTS = "results"

# Rendering
WINDOW_SIZE = 500
FPS = 10
