name: base
channels:
  - pyg
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - appdirs=1.4.4
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - conda=23.1.0
  - conda-content-trust=0.1.3
  - conda-package-handling=2.0.2
  - conda-package-streaming=0.7.0
  - cryptography=38.0.4
  - cudatoolkit=11.3.1
  - flit-core=3.6.0
  - future=0.18.3
  - idna=3.4
  - intel-openmp=2021.4.0
  - jinja2=3.1.2
  - joblib=1.1.1
  - ld_impl_linux-64=2.38
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - markupsafe=2.1.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=1.1.1t
  - packaging=23.0
  - pip=22.3.1
  - pluggy=1.0.0
  - pooch=1.4.0
  - psutil=5.9.0
  - pycosat=0.6.4
  - pycparser=2.21
  - pyg=2.2.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.10.9
  - pytorch=1.12.1
  - pytorch-cluster=1.6.0
  - pytorch-scatter=2.1.0
  - pytorch-sparse=0.6.16
  - pyyaml=6.0
  - readline=8.2
  - requests=2.28.1
  - ruamel.yaml=0.17.21
  - ruamel.yaml.clib=0.2.6
  - scikit-learn=1.2.1
  - scipy=1.10.0
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.40.1
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toolz=0.12.0
  - tqdm=4.64.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.14
  - wheel=0.37.1
  - xz=5.2.10
  - yaml=0.2.5
  - zlib=1.2.13
  - zstandard=0.18.0
