name: simple-agar-gnn
channels:
  - pytorch
  - pyg
  - defaults
dependencies:
  - absl-py=1.3.0
  - aiohttp=3.8.3
  - aiosignal=1.2.0
  - appdirs=1.4.4
  - async-timeout=4.0.2
  - attrs=22.1.0
  - blas=1.0
  - blinker=1.4
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.01.10
  - cachetools=4.2.2
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cryptography=38.0.4
  - ffmpeg=4.2.2
  - fftw=3.3.9
  - flit-core=3.6.0
  - freetype=2.12.1
  - frozenlist=1.3.3
  - gettext=0.21.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - grpcio=1.42.0
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.0.0
  - intel-openmp=2021.4.0
  - jinja2=3.1.2
  - joblib=1.1.1
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - libcxx=14.0.6
  - libdeflate=1.8
  - libffi=3.4.2
  - libiconv=1.16
  - libidn2=2.3.2
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.20.3
  - libtasn1=4.16.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libvpx=1.7.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.1
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - multidict=6.0.2
  - ncurses=6.4
  - nettle=3.7.3
  - numpy=1.23.5
  - numpy-base=1.23.5
  - oauthlib=3.2.1
  - openh264=2.1.1
  - openssl=1.1.1t
  - packaging=22.0
  - pillow=9.3.0
  - pip=22.3.1
  - pooch=1.4.0
  - protobuf=3.20.3
  - psutil=5.9.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyg=2.2.0
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.9.16
  - pytorch=1.13.1
  - pytorch-cluster=1.6.1
  - pytorch-scatter=2.1.1
  - pytorch-sparse=0.6.17
  - readline=8.2
  - requests=2.28.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-learn=1.2.1
  - scipy=1.10.0
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.40.1
  - sympy=1.11.1
  - tensorboard=2.10.0
  - tensorboard-data-server=0.6.1
  - tensorboard-plugin-wit=1.6.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - tqdm=4.64.1
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.14
  - werkzeug=2.2.2
  - wheel=0.38.4
  - x264=1!157.20191217
  - xz=5.2.10
  - yarl=1.8.1
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - cloudpickle==2.2.1
      - filelock==3.10.0
      - gymnasium==0.27.0
      - gymnasium-notices==0.0.1
      - jax-jumpy==0.2.0
      - mpmath==1.3.0
      - networkx==3.0
      - pygame==2.0.0
      - shimmy==0.2.1
      - zipp==3.14.0
